apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: apps
resources:
  - namespace.yaml
  - ../base/
  - gateway.yaml
  - http-route.yaml

patches:
  - path: deployment-patch.yaml
