apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
name: traefik-cluster-role
metadata:
  name: traefik-cluster-role
rules:
  - apiGroups: [""]
    resources: ["services", "pods", "namespaces"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["extensions", "networking.k8s.io"]
    resources: ["ingresses"]
    verbs: ["get", "list", "watch"]
