apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: n8n-ingress-route
  namespace: apps
spec:
  entryPoints:
    - web
    - websecure
  parentRefs:
    - name: traefik-gateway
    - namespace: network
  observability:
    accessLogs: true
    metrics: true
    tracing: true
  routes:
    - match: Host(`n8n.highglade.local`)
      kind: Rule
      services:
        - name: n8n-loadbalancer
          port: 5678
  # tls:
  #   secretName: "staging-ca-tls"
