# base/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: n8n-loadbalancer
spec:
  selector:
    app.kubernetes.io/name: n8n
  ports:
    - protocol: TCP
      port: 5678
      targetPort: 5678
  type: LoadBalancer
