apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml

helmCharts:
  - name: traefik
    repo: https://traefik.github.io/charts
    version: 35.2.0
    releaseName: "traefik"
    includeCRDs: true
    namespace: network
    valuesFile: values.yaml
namespace: network
