apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - gateway-class.yaml
  - gateway.yaml

helmCharts:
  - name: traefik
    repo: https://traefik.github.io/charts
    version: 38.0.1
    releaseName: "traefik"
    includeCRDs: true
    namespace: network
    valuesFile: values.yaml
namespace: network
